In [38]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [39]:
data = pd.read_csv("hiring.csv")
data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [40]:
data.columns

Index(['experience', 'test_score', 'interview_score', 'salary'], dtype='object')

In [41]:
data['experience']

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [42]:
data['experience'][0]

nan

In [43]:
data.experience = data.experience.fillna("zero")
data

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [44]:
from word2number import w2n
data.experience = data.experience.apply(w2n.word_to_num)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [45]:
import math
median_score = math.floor(data.test_score.median())
median_score

8

In [46]:
data.test_score = data.test_score.fillna(median_score)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [48]:
reg = linear_model.LinearRegression(n_jobs=1)
reg.fit(data[["experience","test_score","interview_score"]],data.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [50]:
reg.intercept_

17737.26346433771

In [51]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [54]:
reg.predict([[12,10,10]])

array([112256.91411936])