In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
data = pd.read_csv("homeprices.csv")
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
import math
median_bedrooms = math.floor(data.bedrooms.median())
median_bedrooms

4

In [6]:
data.bedrooms=data.bedrooms.fillna(median_bedrooms)
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg = linear_model.LinearRegression(n_jobs=1)
reg.fit(data[['area','bedrooms','age']],data.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540408

In [10]:
reg.predict([[3300,4,6]])

array([665294.27313441])

In [11]:
 (112.06244194*3300)+(23388.88007794*4)+((-3231.71790863)*6)+221323.00186540408

665294.273127384

In [12]:
import pickle

In [13]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [14]:
with open('model_pickle','rb') as f:
    model = pickle.load(f)

In [15]:
model.predict([[3300,4,6]])

array([665294.27313441])

In [16]:
from sklearn.externals import joblib

D:\Anaconda\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [17]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [19]:
model = joblib.load('model_joblib')

In [20]:
model.predict([[3300,4,6]])

array([665294.27313441])

In [21]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [22]:
model.intercept_

221323.00186540408